name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - " !**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "5.6"
      - uses: "ramsey/composer-install@v3"

      - name: Test with phpunit
        run: |
          ./vendor/bin/phpunit tests
#      - name: Create Release Archive
#        id: semrelease
#        uses: go-semantic-release/action@v1
#        with:
#          # custom-arguments: --provider=gitea
#          hooks: exec
#        env:
#          G_TOKEN: ${{ secrets.G_TOKEN }}
#    env:
#      GITEA_TOKEN: ${{ secrets.G_TOKEN }}
#      GITEA_HOST: ${{ secrets.G_SERVER_URL}}
