name: CI
on:
  push:
    branches:
      - "**"
    tags:
      - " !**"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Install gitea provider for Go Semantic Release
        run: |
          mkdir -p .semrel/$(go env GOOS)_$(go env GOARCH)/provider-gitea/${GITEA_PROVIDER_VER}/ && \
          wget https://github.com/cybercinch/go-semantic-release-provider-gitea/releases/download/v${GITEA_PROVIDER_VER}/go-semantic-release-provider-gitea_v${GITEA_PROVIDER_VER}_linux_amd64 \
          -O .semrel/$(go env GOOS)_$(go env GOARCH)/provider-gitea/${GITEA_PROVIDER_VER}/gitea && \
          chmod a+x .semrel/$(go env GOOS)_$(go env GOARCH)/provider-gitea/${GITEA_PROVIDER_VER}/gitea
        env:
          GITEA_PROVIDER_VER: 1.0.11
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "5.6"
      - uses: "ramsey/composer-install@v3"

      - name: Test with phpunit
        run: |
            phpunit
      - name: Create Release Archive
        id: semrelease
        uses: go-semantic-release/action@v1
        with:
          # custom-arguments: --provider=gitea
          hooks: exec
        env:
          GITEA_TOKEN: ${{ secrets.G_TOKEN }}
          GITEA_HOST: ${{ secrets.G_SERVER_URL}}
    env:
      GITEA_TOKEN: ${{ secrets.G_TOKEN }}
      GITEA_HOST: ${{ secrets.G_SERVER_URL}}
