name: CI
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "5.6"
          extensions: json, curl
          coverage: none  # Disable Xdebug for faster tests

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        uses: ramsey/composer-install@v3
        with:
          composer-options: "--optimize-autoloader"

      - name: Run tests
        run: vendor/bin/phpunit --testdox --verbose

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: semrelease
        uses: go-semantic-release/action@v1
        with:
          hooks: exec
        env:
          GITHUB_TOKEN: ${{ secrets.G_TOKEN }}